# Generated by Django 4.2.6 on 2023-10-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=50)),
                ('dimensiune', models.FloatField()),
                ('price', models.IntegerField()),
                ('data_comenzii', models.DateTimeField(auto_now_add=True)),
                ('bauturi', models.CharField(max_length=40)),
                ('blaturi', models.CharField(max_length=25)),
                ('toping', models.CharField(max_length=40)),
            ],
        ),
    ]
