# Generated by Django 4.2.6 on 2023-10-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_cantitate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='bauturi',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='blaturi',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='cantitate',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='data_comenzii',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='dimensiune',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toping',
        ),
        migrations.AddField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('crocant', 'Crocant'), ('subtire', 'Subtire'), ('pufos', 'Pufos')], default='crocant', max_length=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('mica', 'Mica'), ('medie', 'Medie'), ('mare', 'Mare')], default='medie', max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
