# Generated by Django 4.2.6 on 2023-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizza_type_pizza_alter_pizza_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='type_pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='tip_pizza',
            field=models.CharField(default='Margherita', max_length=50),
        ),
    ]
