# Generated by Django 4.2.6 on 2023-10-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_remove_pizza_type_pizza_pizza_tip_pizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='tip_pizza',
            new_name='type_pizza',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='option',
            field=models.CharField(choices=[('Mica |Blat Normal|30', 'Mica |Blat Normal |30'), ('Medie|Blat Normal|42', 'Medie|Blat Normal |42'), ('Mare |Blat Normal|55', 'Mare |Blat Normal |55'), ('Mare |Blat Special|65', 'Mare |Blat Special|65')], default='Medie|Blat Normal|42', max_length=60),
        ),
    ]
