# Generated by Django 4.2.6 on 2023-10-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_rename_tip_pizza_pizza_type_pizza_alter_pizza_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cantitate',
            field=models.IntegerField(default=0),
        ),
    ]
